name: Fetch Weather Data

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests pandas boto3 google-cloud-storage tqdm

    - name: Install gcloud CLI
      run: |
        sudo apt-get update && sudo apt-get install -y google-cloud-cli
  
    - name: Authenticate with Google Cloud
      run: |
        cat <<EOF > gcp-key.json
        ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        EOF
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project weather-crop-cloud

    - name: Run data fetching script
      run: |
        python fetch_weather_data.py
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        
    - name: Run data analysis script
      run: |
        python analyze_weather_data.py
    
    - name: Commit and push graphs
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add graphs/
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update graphs for $CROP_NAME"
          git push
        fi
      env:
        CROP_NAME: Tomatoes  # Replace with the desired crop name

    - name: Upload to Google Cloud Storage
      run: |
        python upload_to_gcp.py $CROP_NAME
      env:
        CROP_NAME: Tomatoes  # Replace with the desired crop name

    - name: Clean up
      run: rm gcp-key.json